# Generated by Django 2.1.5 on 2019-02-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='guid',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audioclip',
            name='lang',
            field=models.TextField(),
        ),
    ]
