# Generated by Django 2.1.5 on 2019-02-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_modelweights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioclip',
            old_name='file',
            new_name='file_clip',
        ),
        migrations.RenameField(
            model_name='modelweights',
            old_name='file',
            new_name='file_weights',
        ),
    ]
