# Generated by Django 2.1.5 on 2019-02-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_auto_20190206_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelweights',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
