# Generated by Django 2.1.5 on 2019-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0005_modelweights_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='was_correct',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
