# Generated by Django 2.1.5 on 2019-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0006_audioclip_was_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='was_correct',
            field=models.BooleanField(blank=True),
        ),
    ]
